In [1]:
import tensorflow as tf
import warnings
warnings.filterwarnings('ignore')
print(tf.config.list_physical_devices('GPU'))

[]


In [2]:
print(tf.__version__)

2.19.0


In [3]:
from keras.layers import TextVectorization
from tensorflow.keras.preprocessing.text import one_hot


In [4]:
sent=['the glass of milk',
     'the glass of juice',
     'the cup of tea',
     'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good']
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [5]:
voc_size=10000

In [6]:
from keras.layers import TextVectorization

vectorizer = TextVectorization(
    max_tokens=voc_size,
    output_mode="int",
    output_sequence_length=10      #max_len in one_hot tf
#it deefault have post padding we cant to pre
)

vectorizer.adapt(sent)
encoded = vectorizer(sent)
encoded

<tf.Tensor: shape=(7, 10), dtype=int64, numpy=
array([[ 2,  6,  3, 14,  0,  0,  0,  0,  0,  0],
       [ 2,  6,  3, 16,  0,  0,  0,  0,  0,  0],
       [ 2, 18,  3, 13,  0,  0,  0,  0,  0,  0],
       [ 5,  7,  8,  4, 19,  0,  0,  0,  0,  0],
       [ 5,  7,  8,  4, 17,  0,  0,  0,  0,  0],
       [12,  2, 15,  3, 10,  0,  0,  0,  0,  0],
       [ 9, 11, 20,  4,  0,  0,  0,  0,  0,  0]])>

In [7]:
from keras.layers import Embedding
from keras.preprocessing.sequence import pad_sequences
from keras.models import Sequential

In [8]:
#Doing pre padding

from keras.preprocessing.sequence import pad_sequences

encoded_pre = pad_sequences(encoded, maxlen=10, padding='pre')
encoded_pre

array([[ 2,  6,  3, 14,  0,  0,  0,  0,  0,  0],
       [ 2,  6,  3, 16,  0,  0,  0,  0,  0,  0],
       [ 2, 18,  3, 13,  0,  0,  0,  0,  0,  0],
       [ 5,  7,  8,  4, 19,  0,  0,  0,  0,  0],
       [ 5,  7,  8,  4, 17,  0,  0,  0,  0,  0],
       [12,  2, 15,  3, 10,  0,  0,  0,  0,  0],
       [ 9, 11, 20,  4,  0,  0,  0,  0,  0,  0]], dtype=int32)

In [9]:
dim = 10          # Embedding vector size
voc_sizvoc_size = len(vectorizer.get_vocabulary())  # automatically includes padding token
max_len = 10      # Padded sequence length

model = Sequential()
model.add(Embedding(
    input_dim=voc_size, 
    output_dim=dim, 
    input_length=max_len
))

model.compile('adam','mse')


In [10]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [11]:
print(model.predict(encoded))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 109ms/step
[[[-0.01013622  0.02794946  0.01247234 -0.02379588  0.04560517
    0.04872077 -0.00212901  0.04467858  0.04722471  0.01210932]
  [-0.03058535 -0.0036632   0.0228514   0.03405917 -0.02220379
   -0.01336274  0.0378213  -0.04055238  0.02273954  0.00719532]
  [ 0.04135231 -0.02167984 -0.03954264  0.03487064  0.0237519
   -0.01311675 -0.03033613 -0.02053604 -0.02952139  0.03020852]
  [ 0.04194948 -0.04558101 -0.01319742  0.0418802  -0.01026789
   -0.01606715  0.02796164 -0.0390031  -0.03078178 -0.0079539 ]
  [ 0.03262908 -0.03352459 -0.01840084 -0.01179373  0.03605152
   -0.04482701 -0.0090818   0.04790628  0.03939957 -0.00052189]
  [ 0.03262908 -0.03352459 -0.01840084 -0.01179373  0.03605152
   -0.04482701 -0.0090818   0.04790628  0.03939957 -0.00052189]
  [ 0.03262908 -0.03352459 -0.01840084 -0.01179373  0.03605152
   -0.04482701 -0.0090818   0.04790628  0.03939957 -0.00052189]
  [ 0.03262908 -0.03352459 -0.01840084 -0.01179373  0.03605152
   -0.0448